version: "3"
services:
  master:
    extends:
      file: docker/docker-compose.master.yml
      service: master
    container_name: master
    hostname: master
    environment:
      MYSQL_ROOT_PASSWORD: masterpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: masteruser
      MYSQL_PASSWORD: masterpassword
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/master.cnf:/etc/my.cnf
      - ./data/master:/var/lib/mysql
    networks:
      - mysql_network
  slave1:
    extends:
      file: docker/docker-compose.slave.yml
      service: slave
    container_name: slave1
    hostname: slave1
    environment:
      MYSQL_ROOT_PASSWORD: slavepassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: slaveuser
      MYSQL_PASSWORD: slavepassword
      MYSQL_MASTER_HOST: master
      MYSQL_MASTER_PORT: 3306
      MYSQL_MASTER_USER: masteruser
      MYSQL_MASTER_PASSWORD: masterpassword
    ports:
      - "3307:3306"
    volumes:
      - ./conf/mysql/slave1.cnf:/etc/my.cnf
      - ./data/slave1:/var/lib/mysql
    networks:
      - mysql_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    hostname: phpmyadmin
    ports:
      - "80:80"
    volumes:
      - ./conf/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./data/phpmyadmin/:/srv/phpmyadmin/
    environment:
      UPLOAD_LIMIT: "100M"
      APACHE_PORT: 80
    networks:
      - mysql_network

networks:
  mysql_network:
    name: mysql_network
    ipam:
      config:
        - subnet: "172.6.0.0/16"
