version: "3"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    hostname: phpmyadmin
    ports:
      - "80:80"
    volumes:
      - ./conf/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./data/phpmyadmin/:/srv/phpmyadmin/
    environment:
      UPLOAD_LIMIT: "100M"
      APACHE_PORT: 80
    networks:
      - mysql_network

networks:
  mysql_network:
    name: mysql_network
    ipam:
      config:
        - subnet: "172.6.0.0/16"
